### ISSUE TITLE
ModuleNotFoundError: No module named 'mffusion.utils.mlgp_hook'

### ISSUE THREAD

**Issue by M2LabOrg** [IceLab-X/FidelityFusion#6]
Hi,

When I run `gar_demo.py`, I get the following error:

```
Traceback (most recent call last):
  File "gar_demo.py", line 13, in <module>
    from mffusion.modules.gp_module.hogp import HOGP_MODULE
  File "/Users/skl/Documents/GitHub/UoS_dissertation/FidelityFusion/mffusion/modules/gp_module/hogp.py", line 17, in <module>
    from mffusion.utils.mlgp_hook import set_function_as_module_to_catch_error
ModuleNotFoundError: No module named 'mffusion.utils.mlgp_hook'
```

The `mlgp_hook` file is not found under utils. The code works well when I comment this line in `hogp.py:`

`from mffusion.utils.mlgp_hook import set_function_as_module_to_catch_error`

Where can I find mlgp_hook?

Thanks!

Michel

**Comment by zen-xingle** [comment]
Hi Michel,

The `mlgp_hook` file has been removed, but the code `from mffusion.utils.mlgp_hook import set_function_as_module_to_catch_error` was not removed properly.

The error has been fixed in the latest commit. Please pull the latest code and give it a try.

Thank you for bringing this issue to our attention!

Zen

**Comment by M2LabOrg** [comment]
Hi Zen,
Thank you so much!
Best wishes, 
Michel
